import { format } from "date-fns"
import { ptBR } from "date-fns/locale"

export type AuditLog = {
  id: string
  timestamp: string // ISO string
  eventType: string
  relatedId: string | null // CPF or reference ID
  origin: string // e.g., "Frontend", "Backend", "Admin Panel"
  status: "Sucesso" | "Erro" | "Atenção"
  description: string
  hash: string
  executedBy: string // User who performed the action
  ipAddress: string
  userAgent: string
  requestPayload: Record<string, any> | null
  responsePayload: Record<string, any> | null
  previousState: Record<string, any> | null
  currentState: Record<string, any> | null
}

export const mockAuditLogs: AuditLog[] = [
  {
    id: "log_001",
    timestamp: new Date(2024, 5, 15, 10, 30, 0).toISOString(),
    eventType: "Login",
    relatedId: "123.456.789-00",
    origin: "Frontend",
    status: "Sucesso",
    description: "Usuário 'joao.silva' realizou login com sucesso.",
    hash: "abc123def456",
    executedBy: "joao.silva",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { username: "joao.silva" },
    responsePayload: { status: "authenticated", userId: "user_123" },
    previousState: null,
    currentState: null,
  },
  {
    id: "log_002",
    timestamp: new Date(2024, 5, 15, 11, 0, 0).toISOString(),
    eventType: "Transação",
    relatedId: "trans_789",
    origin: "Backend",
    status: "Sucesso",
    description: "Transação de R$ 50,00 processada para o usuário 'maria.souza'.",
    hash: "ghi789jkl012",
    executedBy: "sistema_pagamento",
    ipAddress: "10.0.0.5",
    userAgent: "Node.js/v18.12.0",
    requestPayload: { userId: "user_456", amount: 50, type: "deposit" },
    responsePayload: { transactionId: "trans_789", status: "completed" },
    previousState: { balance: 100 },
    currentState: { balance: 150 },
  },
  {
    id: "log_003",
    timestamp: new Date(2024, 5, 15, 11, 15, 0).toISOString(),
    eventType: "Erro no sistema",
    relatedId: null,
    origin: "Backend",
    status: "Erro",
    description: "Falha ao conectar ao banco de dados de usuários.",
    hash: "mno345pqr678",
    executedBy: "sistema_core",
    ipAddress: "10.0.0.1",
    userAgent: "Java/11.0.1",
    requestPayload: null,
    responsePayload: { error: "DB_CONNECTION_FAILED", message: "Timeout connecting to PostgreSQL" },
    previousState: null,
    currentState: null,
  },
  {
    id: "log_004",
    timestamp: new Date(2024, 5, 15, 12, 0, 0).toISOString(),
    eventType: "Raspadinha ativada",
    relatedId: "scratch_999",
    origin: "Frontend",
    status: "Sucesso",
    description: "Raspadinha 'Super Raspepix' ativada pelo usuário 'carlos.pereira'.",
    hash: "stu901vwx234",
    executedBy: "carlos.pereira",
    ipAddress: "172.16.0.50",
    userAgent:
      "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1",
    requestPayload: { scratchCardId: "scratch_999", userId: "user_789" },
    responsePayload: { status: "activated", prize: null },
    previousState: { status: "pending" },
    currentState: { status: "active" },
  },
  {
    id: "log_005",
    timestamp: new Date(2024, 5, 15, 13, 0, 0).toISOString(),
    eventType: "Entrega de prêmio",
    relatedId: "prize_123",
    origin: "Admin Panel",
    status: "Atenção",
    description: "Tentativa de entrega de prêmio para usuário com dados incompletos.",
    hash: "yza567bcd890",
    executedBy: "admin.user",
    ipAddress: "192.168.1.1",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { prizeId: "prize_123", userId: "user_101", deliveryMethod: "bank_transfer" },
    responsePayload: { status: "pending_review", reason: "missing_bank_details" },
    previousState: { deliveryStatus: "pending" },
    currentState: { deliveryStatus: "on_hold" },
  },
  {
    id: "log_006",
    timestamp: new Date(2024, 5, 15, 14, 0, 0).toISOString(),
    eventType: "Criação de sorteio",
    relatedId: "draw_001",
    origin: "Admin Panel",
    status: "Sucesso",
    description: "Novo sorteio 'Sorteio Mensal Junho' criado.",
    hash: "efg123hij456",
    executedBy: "admin.user",
    ipAddress: "192.168.1.1",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { name: "Sorteio Mensal Junho", date: "2024-06-30", prize: "Carro" },
    responsePayload: { drawId: "draw_001", status: "created" },
    previousState: null,
    currentState: { status: "active" },
  },
  {
    id: "log_007",
    timestamp: new Date(2024, 5, 15, 15, 0, 0).toISOString(),
    eventType: "Alteração de status de usuário",
    relatedId: "user_123",
    origin: "Admin Panel",
    status: "Sucesso",
    description: "Status do usuário 'joao.silva' alterado para 'ativo'.",
    hash: "klm789nop012",
    executedBy: "admin.user",
    ipAddress: "192.168.1.1",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { userId: "user_123", newStatus: "active" },
    responsePayload: { userId: "user_123", oldStatus: "inactive", newStatus: "active" },
    previousState: { status: "inactive" },
    currentState: { status: "active" },
  },
  {
    id: "log_008",
    timestamp: new Date(2024, 5, 15, 16, 0, 0).toISOString(),
    eventType: "Login suspeito",
    relatedId: "user_456",
    origin: "Backend",
    status: "Atenção",
    description: "Tentativa de login de 'maria.souza' de um IP incomum.",
    hash: "qrs345tuv678",
    executedBy: "sistema_seguranca",
    ipAddress: "203.0.113.45",
    userAgent:
      "Mozilla/5.0 (Linux; Android 10; SM-G973F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
    requestPayload: { username: "maria.souza" },
    responsePayload: { status: "blocked", reason: "unusual_ip" },
    previousState: null,
    currentState: null,
  },
  {
    id: "log_009",
    timestamp: new Date(2024, 5, 15, 17, 0, 0).toISOString(),
    eventType: "Geração de número da sorte",
    relatedId: "ticket_555",
    origin: "Backend",
    status: "Sucesso",
    description: "Número da sorte gerado para o bilhete 'ticket_555'.",
    hash: "wxy901zab234",
    executedBy: "sistema_sorteio",
    ipAddress: "10.0.0.2",
    userAgent: "Python/3.9",
    requestPayload: { ticketId: "ticket_555" },
    responsePayload: { luckyNumber: "123456", status: "generated" },
    previousState: { luckyNumber: null },
    currentState: { luckyNumber: "123456" },
  },
  {
    id: "log_010",
    timestamp: new Date(2024, 5, 15, 18, 0, 0).toISOString(),
    eventType: "Sorteio processado",
    relatedId: "draw_001",
    origin: "Backend",
    status: "Sucesso",
    description: "Sorteio 'Sorteio Mensal Junho' processado com sucesso. Vencedor: 'user_789'.",
    hash: "cde567fgh890",
    executedBy: "sistema_sorteio",
    ipAddress: "10.0.0.2",
    userAgent: "Python/3.9",
    requestPayload: { drawId: "draw_001" },
    responsePayload: { winnerId: "user_789", prizeId: "prize_123", status: "completed" },
    previousState: { status: "pending" },
    currentState: { status: "completed" },
  },
  {
    id: "log_011",
    timestamp: new Date(2024, 5, 15, 19, 0, 0).toISOString(),
    eventType: "Suspensão/Exclusão",
    relatedId: "user_101",
    origin: "Admin Panel",
    status: "Sucesso",
    description: "Usuário 'ana.costa' suspenso por atividade suspeita.",
    hash: "ijk123lmn456",
    executedBy: "admin.user",
    ipAddress: "192.168.1.1",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { userId: "user_101", action: "suspend", reason: "suspicious_activity" },
    responsePayload: { userId: "user_101", status: "suspended" },
    previousState: { status: "active" },
    currentState: { status: "suspended" },
  },
  {
    id: "log_012",
    timestamp: new Date(2024, 5, 15, 20, 0, 0).toISOString(),
    eventType: "Edição alterada",
    relatedId: "content_page_about",
    origin: "Admin Panel",
    status: "Sucesso",
    description: "Página 'Sobre Nós' editada.",
    hash: "opq789rst012",
    executedBy: "admin.editor",
    ipAddress: "192.168.1.2",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { pageId: "content_page_about", changes: { title: "Novo Título" } },
    responsePayload: { status: "updated" },
    previousState: { title: "Título Antigo" },
    currentState: { title: "Novo Título" },
  },
  {
    id: "log_013",
    timestamp: new Date(2024, 5, 16, 9, 0, 0).toISOString(),
    eventType: "Login",
    relatedId: "111.222.333-44",
    origin: "Frontend",
    status: "Sucesso",
    description: "Usuário 'pedro.gomes' realizou login com sucesso.",
    hash: "uvw345xyz678",
    executedBy: "pedro.gomes",
    ipAddress: "192.168.1.101",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { username: "pedro.gomes" },
    responsePayload: { status: "authenticated", userId: "user_111" },
    previousState: null,
    currentState: null,
  },
  {
    id: "log_014",
    timestamp: new Date(2024, 5, 16, 9, 30, 0).toISOString(),
    eventType: "Transação",
    relatedId: "trans_101",
    origin: "Backend",
    status: "Erro",
    description: "Falha na transação de R$ 20,00 para o usuário 'pedro.gomes'. Saldo insuficiente.",
    hash: "abc901def234",
    executedBy: "sistema_pagamento",
    ipAddress: "10.0.0.5",
    userAgent: "Node.js/v18.12.0",
    requestPayload: { userId: "user_111", amount: 20, type: "withdraw" },
    responsePayload: { transactionId: "trans_101", status: "failed", reason: "insufficient_funds" },
    previousState: { balance: 10 },
    currentState: { balance: 10 },
  },
  {
    id: "log_015",
    timestamp: new Date(2024, 5, 16, 10, 0, 0).toISOString(),
    eventType: "Sistema",
    relatedId: null,
    origin: "Backend",
    status: "Sucesso",
    description: "Backup diário do banco de dados concluído.",
    hash: "ghi567jkl890",
    executedBy: "sistema_backup",
    ipAddress: "10.0.0.3",
    userAgent: "Bash/5.0",
    requestPayload: null,
    responsePayload: { status: "completed", filesBackedUp: 100 },
    previousState: null,
    currentState: null,
  },
  {
    id: "log_016",
    timestamp: new Date(2024, 5, 16, 10, 30, 0).toISOString(),
    eventType: "Alteração de prêmio",
    relatedId: "prize_456",
    origin: "Admin Panel",
    status: "Sucesso",
    description: "Prêmio 'Viagem para o Caribe' alterado para 'Viagem para Fernando de Noronha'.",
    hash: "mno123pqr456",
    executedBy: "admin.user",
    ipAddress: "192.168.1.1",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { prizeId: "prize_456", newName: "Viagem para Fernando de Noronha" },
    responsePayload: { status: "updated" },
    previousState: { name: "Viagem para o Caribe" },
    currentState: { name: "Viagem para Fernando de Noronha" },
  },
  {
    id: "log_017",
    timestamp: new Date(2024, 5, 16, 11, 0, 0).toISOString(),
    eventType: "Login suspeito",
    relatedId: "user_111",
    origin: "Backend",
    status: "Atenção",
    description: "Tentativa de login de 'pedro.gomes' de um dispositivo não reconhecido.",
    hash: "stu789vwx012",
    executedBy: "sistema_seguranca",
    ipAddress: "187.1.2.3",
    userAgent: "Dalvik/2.1.0 (Linux; U; Android 9; SM-A505FN Build/PPR1.180610.011)",
    requestPayload: { username: "pedro.gomes" },
    responsePayload: { status: "challenge_required", reason: "unrecognized_device" },
    previousState: null,
    currentState: null,
  },
  {
    id: "log_018",
    timestamp: new Date(2024, 5, 16, 12, 0, 0).toISOString(),
    eventType: "Transação",
    relatedId: "trans_202",
    origin: "Frontend",
    status: "Sucesso",
    description: "Depósito de R$ 100,00 via Pix para o usuário 'joao.silva'.",
    hash: "yza345bcd678",
    executedBy: "joao.silva",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { userId: "user_123", amount: 100, type: "deposit", method: "pix" },
    responsePayload: { transactionId: "trans_202", status: "completed" },
    previousState: { balance: 150 },
    currentState: { balance: 250 },
  },
  {
    id: "log_019",
    timestamp: new Date(2024, 5, 16, 13, 0, 0).toISOString(),
    eventType: "Raspadinha ativada",
    relatedId: "scratch_100",
    origin: "Frontend",
    status: "Sucesso",
    description: "Raspadinha 'Mega Sorte' ativada pelo usuário 'maria.souza'.",
    hash: "efg901hij234",
    executedBy: "maria.souza",
    ipAddress: "172.16.0.51",
    userAgent: "Mozilla/5.0 (Android 11; Mobile; rv:109.0) Gecko/117.0 Firefox/117.0",
    requestPayload: { scratchCardId: "scratch_100", userId: "user_456" },
    responsePayload: { status: "activated", prize: "R$ 10,00" },
    previousState: { status: "pending" },
    currentState: { status: "active" },
  },
  {
    id: "log_020",
    timestamp: new Date(2024, 5, 16, 14, 0, 0).toISOString(),
    eventType: "Entrega de prêmio",
    relatedId: "prize_789",
    origin: "Admin Panel",
    status: "Sucesso",
    description: "Prêmio de R$ 500,00 entregue ao usuário 'carlos.pereira'.",
    hash: "klm567nop890",
    executedBy: "admin.user",
    ipAddress: "192.168.1.1",
    userAgent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    requestPayload: { prizeId: "prize_789", userId: "user_789", deliveryMethod: "pix" },
    responsePayload: { status: "delivered" },
    previousState: { deliveryStatus: "pending" },
    currentState: { deliveryStatus: "delivered" },
  },
]

export const eventTypes = [
  "Todos os Tipos",
  "Entrega de prêmio",
  "Geração de número da sorte",
  "Sorteio processado",
  "Sistema",
  "Erro no sistema",
  "Suspensão/Exclusão",
  "Raspadinha ativada",
  "Login suspeito",
  "Login",
  "Criação de sorteio",
  "Alteração de prêmio",
  "Alteração de status de usuário",
  "Transação",
  "Edição alterada",
]

// Utility function to format date for display
export const formatAuditDate = (isoString: string) => {
  return format(new Date(isoString), "dd/MM/yyyy HH:mm:ss", { locale: ptBR })
}
